services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=markets'
      - 'POSTGRES_PASSWORD=my_password'
      - 'POSTGRES_USER=my_user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
